apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: example
spec:
  spec:
    devices:
      requests:
        - name: example-claim
          exactly:
            deviceClassName: gpu.example.com
            selectors:
              - cel:
                  expression: |-
                    device.attributes["gpu.example.com"].model == "LATEST-GPU-MODEL"
                    && device.capacity["gpu.example.com"].memory == quantity("80Gi")
